spring:
  profiles:
    active: local
  application:
    name: 11th-street

server:
  shutdown: graceful

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-seconds: ${JWT_ACCESS_TOKEN_VALIDITY_SECONDS}
  refresh-token-validity-seconds: ${JWT_REFRESH_TOKEN_VALIDITY_SECONDS}
