server:
  port: ${SERVER_PORT:8080}
  shutdown: ${SERVER_SHUTDOWN:graceful}

spring:
  application:
    name: 11th-street
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    open-in-view: ${JPA_OPEN_IN_VIEW:false}

  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: ${FLYWAY_LOCATIONS:classpath:db/migration}
    validate-on-migrate: ${FLYWAY_VALIDATE_ON_MIGRATE:true}

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health
      path-mapping:
        health: health
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,db,redis
        liveness:
          include: livenessState

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-seconds: ${JWT_ACCESS_TOKEN_VALIDITY_SECONDS}
  refresh-token-validity-seconds: ${JWT_REFRESH_TOKEN_VALIDITY_SECONDS}
